set(LIBAVRC++_NAME                      "Arduino Uno")
set(LIBAVRC++_UPLOAD_PROTOCOL           "arduino")
set(LIBAVRC++_UPLOAD_MAXIMUM_SIZE       "32256")
set(LIBAVRC++_UPLOAD_SPEED              "115200")
set(LIBAVRC++_BOOTLOADER_LOW_FUSES      "0xff")
set(LIBAVRC++_BOOTLOADER_HIGH_FUSES     "0xde")
set(LIBAVRC++_BOOTLOADER_EXTENDED_FUSES "0x05")
set(LIBAVRC++_BOOTLOADER_PATH           "optiboot")
set(LIBAVRC++_BOOTLOADER_FILE           "optiboot_atmega328.hex")
set(LIBAVRC++_BOOTLOADER_UNLOCK_BITS    "0x3F")
set(LIBAVRC++_BOOTLOADER_LOCK_BITS      "0x0F")
set(LIBAVRC++_BUILD_MCU                 "atmega328p")
set(LIBAVRC++_BUILD_F_CPU               "16000000L")
set(LIBAVRC++_BUILD_CORE                "arduino")
set(LIBAVRC++_BUILD_VARIANT             "standard")
set(LIBAVRC++_UPLOAD_DEFAULT_PORT       "/dev/ttyACM0")