set(LIBAVRC++_NAME                      "Arduino Pro Mini 3.3V/8MHz ATmega328")
set(LIBAVRC++_UPLOAD_PROTOCOL           "arduino")
set(LIBAVRC++_UPLOAD_MAXIMUM_SIZE       "30720")
set(LIBAVRC++_UPLOAD_SPEED              "57600")

set(LIBAVRC++_BOOTLOADER_LOW_FUSES      "0xff")
set(LIBAVRC++_BOOTLOADER_HIGH_FUSES     "0xda")
set(LIBAVRC++_BOOTLOADER_EXTENDED_FUSES "0x05")
set(LIBAVRC++_BOOTLOADER_PATH           "atmega")
set(LIBAVRC++_BOOTLOADER_FILE           "ATmegaBOOT_168_atmega328_pro_8MHz.hex")
set(LIBAVRC++_BOOTLOADER_UNLOCK_BITS    "0x3F")
set(LIBAVRC++_BOOTLOADER_LOCK_BITS      "0x0F")
set(LIBAVRC++_BUILD_MCU                 "atmega328p")
set(LIBAVRC++_BUILD_F_CPU               "8000000L")
set(LIBAVRC++_BUILD_VID                 "0x1B4F")
set(LIBAVRC++_BUILD_PID                 "0x9204")
set(LIBAVRC++_BUILD_CORE                "arduino:arduino")
set(LIBAVRC++_BUILD_VARIANT             "standard")
set(LIBAVRC++_UPLOAD_DEFAULT_PORT       "/dev/ttyACM0")